# Generated by Django 2.0.2 on 2018-03-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='date',
            field=models.DateField(unique=True, verbose_name='date of the election'),
        ),
    ]
