# Generated by Django 2.0.2 on 2018-03-27 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_party_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='number',
        ),
    ]
