# Generated by Django 2.0.2 on 2018-03-23 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180323_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayedIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=64)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Match')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Member')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='playedin',
            unique_together={('member', 'team', 'match')},
        ),
    ]
