# Generated by Django 2.0.2 on 2018-03-19 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180319_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'managed': False},
        ),
    ]
