# Generated by Django 2.0.2 on 2018-04-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180403_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='scoreA',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='scoreB',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
