# Generated by Django 2.0.2 on 2018-03-19 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180319_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={},
        ),
    ]
