# Generated by Django 2.0.2 on 2018-04-04 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180403_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='BracketNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('sibling_index', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='tournament',
        ),
        migrations.AddField(
            model_name='bracketnode',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Match'),
        ),
        migrations.AddField(
            model_name='bracketnode',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tournament'),
        ),
        migrations.AlterUniqueTogether(
            name='bracketnode',
            unique_together={('tournament', 'level', 'sibling_index')},
        ),
    ]
