# Generated by Django 2.0.2 on 2018-03-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_court_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='endDate',
            field=models.DateField(blank=True, null=True, unique=True, verbose_name='end date of tournament'),
        ),
    ]
