# Generated by Django 2.0.2 on 2018-03-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tournament_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='startDate',
            field=models.DateTimeField(verbose_name='date time started'),
        ),
    ]
