# Generated by Django 2.0.2 on 2018-03-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180319_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(primary_key=True, serialize=False, verbose_name='date of announcement'),
        ),
        migrations.AlterUniqueTogether(
            name='announcement',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='id',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='time',
        ),
    ]
