# Generated by Django 2.0.2 on 2018-03-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180326_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(unique=True, verbose_name='date of announcement'),
        ),
        migrations.AlterField(
            model_name='court',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='election',
            name='date',
            field=models.DateField(unique=True, verbose_name='date of the election'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(unique=True, verbose_name='date of session'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateField(unique=True, verbose_name='date of tournament'),
        ),
    ]
