# Generated by Django 2.0.2 on 2018-03-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180319_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='endDate',
            field=models.DateField(blank=True, null=True, verbose_name='election end date'),
        ),
    ]
