# Generated by Django 2.0.2 on 2018-03-27 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180327_2236'),
    ]

    operations = [
        migrations.RenameField('Match', 'startDate', 'startDateTime')
    ]
