# Generated by Django 2.0.2 on 2018-03-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180327_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedmatch',
            name='endDate',
            field=models.DateTimeField(verbose_name='date time ended'),
        ),
    ]
