# Generated by Django 2.0.2 on 2018-03-20 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_election_enddate'),
    ]

    operations = [
        migrations.RenameField('Team', 'memberA', 'member1'),
        migrations.RenameField('Team', 'memberB', 'member2'),
    ]
