# Generated by Django 2.0.2 on 2018-03-20 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180320_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, verbose_name='date of session')),
                ('number_of_courts', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='member1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member1', to='api.Member'),
        ),
        migrations.AlterField(
            model_name='team',
            name='member2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member2', to='api.Member'),
        ),
    ]
