# Generated by Django 2.0.2 on 2018-03-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180326_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
