# Generated by Django 2.0.1 on 2018-04-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180404_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='picture',
            field=models.TextField(null=True),
        ),
    ]
