# Generated by Django 2.0.2 on 2018-03-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180327_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishedmatch',
            name='match_ptr',
        ),
        migrations.AddField(
            model_name='match',
            name='endDateTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date time ended'),
        ),
        migrations.DeleteModel(
            name='FinishedMatch',
        ),
    ]
