# Generated by Django 2.0.1 on 2018-04-16 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_member_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='court',
        ),
        migrations.AddField(
            model_name='court',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Match'),
        ),
        migrations.AlterField(
            model_name='member',
            name='picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
