# Generated by Django 2.0.2 on 2018-03-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180320_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bio',
            field=models.CharField(default='', max_length=500),
        ),
    ]
