# Generated by Django 2.0.1 on 2018-04-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180416_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='in_tournament',
            field=models.BooleanField(default=False),
        ),
    ]
