# Generated by Django 2.0.2 on 2018-03-01 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('formerBoardMember', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('interested_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='badminton.Interested')),
                ('level', models.IntegerField(default=0)),
                ('private', models.BooleanField(default=False)),
                ('dateJoined', models.DateField(verbose_name='date joined')),
            ],
            bases=('badminton.interested',),
        ),
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('member_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='badminton.Member')),
                ('job', models.CharField(choices=[('PRESIDENT', 'President'), ('TREASURER', 'Treasurer'), ('OFFICER', 'Officer')], max_length=64)),
            ],
            bases=('badminton.member',),
        ),
    ]
