# Generated by Django 2.0.2 on 2018-03-01 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badminton', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(choices=[('PRESIDENT', 'President'), ('TREASURER', 'Treasurer'), ('OFFICER', 'Officer')], max_length=64)),
                ('pitch', models.CharField(max_length=500)),
                ('campaigner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badminton.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date of the election')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField(verbose_name='date started')),
                ('scoreA', models.IntegerField()),
                ('scoreB', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CASUAL', 'Casual'), ('RANKED', 'Ranked'), ('KOTH', 'King of the Hill')], max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberA', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberA', to='badminton.Member')),
                ('memberB', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberB', to='badminton.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date of tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badminton.Election')),
                ('votee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votee', to='badminton.Member')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter', to='badminton.Member')),
            ],
        ),
        migrations.CreateModel(
            name='FinishedMatch',
            fields=[
                ('match_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='badminton.Match')),
                ('endDate', models.DateTimeField(verbose_name='date ended')),
            ],
            bases=('badminton.match',),
        ),
        migrations.AddField(
            model_name='match',
            name='court',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='badminton.Court'),
        ),
        migrations.AddField(
            model_name='match',
            name='teamA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamA', to='badminton.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='teamB',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamB', to='badminton.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='badminton.Tournament'),
        ),
        migrations.AddField(
            model_name='court',
            name='queue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='badminton.Queue'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badminton.Election'),
        ),
        migrations.AddField(
            model_name='member',
            name='queue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='badminton.Queue'),
        ),
    ]
