# Generated by Django 2.0.2 on 2018-03-01 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badminton', '0002_auto_20180301_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='queue',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='badminton.Queue'),
        ),
    ]
