# Generated by Django 2.0.2 on 2018-03-17 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, verbose_name='date of announcement')),
                ('title', models.CharField(max_length=64)),
                ('entry', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(choices=[('PRESIDENT', 'President'), ('TREASURER', 'Treasurer'), ('OFFICER', 'Officer')], max_length=64)),
                ('pitch', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, verbose_name='date of the election')),
            ],
        ),
        migrations.CreateModel(
            name='Interested',
            fields=[
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('formerBoardMember', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateTimeField(verbose_name='date started')),
                ('scoreA', models.IntegerField()),
                ('scoreB', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('type', models.CharField(choices=[('CASUAL', 'Casual'), ('RANKED', 'Ranked'), ('KOTH', 'King of the Hill')], max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, verbose_name='date of tournament')),
            ],
        ),
        migrations.CreateModel(
            name='FinishedMatch',
            fields=[
                ('match_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Match')),
                ('endDate', models.DateTimeField(verbose_name='date ended')),
            ],
            bases=('api.match',),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('interested_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Interested')),
                ('level', models.IntegerField(default=0)),
                ('private', models.BooleanField(default=False)),
                ('dateJoined', models.DateField(verbose_name='date joined')),
            ],
            bases=('api.interested',),
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Election')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Court'),
        ),
        migrations.AddField(
            model_name='match',
            name='teamA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamA', to='api.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='teamB',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamB', to='api.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Tournament'),
        ),
        migrations.AddField(
            model_name='court',
            name='queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Queue'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Election'),
        ),
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('member_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Member')),
                ('job', models.CharField(choices=[('PRESIDENT', 'President'), ('TREASURER', 'Treasurer'), ('OFFICER', 'Officer')], max_length=64)),
            ],
            bases=('api.member',),
        ),
        migrations.AddField(
            model_name='votes',
            name='votee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votee', to='api.Member'),
        ),
        migrations.AddField(
            model_name='votes',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter', to='api.Member', unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='memberA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberA', to='api.Member'),
        ),
        migrations.AddField(
            model_name='team',
            name='memberB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberB', to='api.Member'),
        ),
        migrations.AddField(
            model_name='member',
            name='queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Queue'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaigner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Member'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('memberA', 'memberB')},
        ),
    ]
